// <auto-generated />
using System;
using Ironau_Dzuris.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ironau_Dzuris.Db.Migrations.Words
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240612231530_InitWordsDb")]
    partial class InitWordsDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ironau_Dzuris.Db.Models.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phrase_os")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phrase_ru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phrases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Phrase_os = "Дæ ном куыд у?",
                            Phrase_ru = "Как тебя зовут?",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Phrase_os = "Дæ(Уæ) рáйсом хорз",
                            Phrase_ru = "Доброе утро",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Phrase_os = "Дæ и́зæр хорз",
                            Phrase_ru = "Добрый вечер",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Phrase_os = "Дæ бон хорз",
                            Phrase_ru = "Добрый день",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Phrase_os = "Хæрзǽхсæв",
                            Phrase_ru = "Спокойной ночи",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Phrase_os = "О",
                            Phrase_ru = "Да",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Phrase_os = "Нæ",
                            Phrase_ru = "Нет",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Phrase_os = "Хорз",
                            Phrase_ru = "Хорошо",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Phrase_os = "Бузныг",
                            Phrase_ru = "Спасибо",
                            Theme = "Общение"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Phrase_os = "Стыр Бузныг",
                            Phrase_ru = "Большое спасибо",
                            Theme = "Общение"
                        });
                });

            modelBuilder.Entity("Ironau_Dzuris.Db.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-aaaa-aaaa-aaaa-000000000000"),
                            Email = "admin@admin.ru",
                            Name = "admin",
                            Password = "aDMiN",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("Ironau_Dzuris.Db.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word_os")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word_ru")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            ImagePath = "~/images/words/Дерево.jpg",
                            Theme = "",
                            Word_os = "Бæлас",
                            Word_ru = "Дерево"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            ImagePath = "~/images/words/Мальчик.jpg",
                            Theme = "",
                            Word_os = "Лæппу",
                            Word_ru = "Мальчик"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            ImagePath = "~/images/words/Дом.jpg",
                            Theme = "",
                            Word_os = "Хæдзар",
                            Word_ru = "Дом"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            ImagePath = "~/images/words/Кот.jpg",
                            Theme = "",
                            Word_os = "Гæды",
                            Word_ru = "Кот"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            ImagePath = "~/images/words/Собака.jpg",
                            Theme = "",
                            Word_os = "Куыдз",
                            Word_ru = "Собака"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            ImagePath = "~/images/words/Стол.jpg",
                            Theme = "",
                            Word_os = "Фынг",
                            Word_ru = "Стол"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            ImagePath = "~/images/words/Книга.jpg",
                            Theme = "",
                            Word_os = "Чиныг",
                            Word_ru = "Книга"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            ImagePath = "~/images/words/Яблоко.jpg",
                            Theme = "",
                            Word_os = "Фæткъуы",
                            Word_ru = "Яблоко"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            ImagePath = "~/images/words/Мяч.jpg",
                            Theme = "",
                            Word_os = "Пурти",
                            Word_ru = "Мяч"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            ImagePath = "~/images/words/Солнце.jpg",
                            Theme = "",
                            Word_os = "Хур",
                            Word_ru = "Солнце"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            ImagePath = "~/images/words/Луна.jpg",
                            Theme = "",
                            Word_os = "Мæй",
                            Word_ru = "Луна"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            ImagePath = "~/images/words/Девочка.jpg",
                            Theme = "",
                            Word_os = "Чызг",
                            Word_ru = "Девочка"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            ImagePath = "~/images/words/Лопата.jpg",
                            Theme = "",
                            Word_os = "Бел",
                            Word_ru = "Лопата"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            ImagePath = "~/images/words/Вода.jpg",
                            Theme = "",
                            Word_os = "Дон",
                            Word_ru = "Вода"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            ImagePath = "~/images/words/Вишня.jpg",
                            Theme = "",
                            Word_os = "Бал",
                            Word_ru = "Вишня"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            ImagePath = "~/images/words/Рыба.jpg",
                            Theme = "",
                            Word_os = "Кæсаг",
                            Word_ru = "Рыба"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            ImagePath = "~/images/words/Огурец.jpg",
                            Theme = "",
                            Word_os = "Джитъри",
                            Word_ru = "Огурец"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            ImagePath = "~/images/words/Индюк.jpg",
                            Theme = "",
                            Word_os = "Гогыз",
                            Word_ru = "Индюк"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            ImagePath = "~/images/words/Дверь.png",
                            Theme = "",
                            Word_os = "Дуар",
                            Word_ru = "Дверь"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
